# Generated by Django 3.0.4 on 2020-03-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200318_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='content',
            new_name='content_object',
        ),
    ]
